openapi: 3.0.0
info:
  title: Product API
  description: API для управления продуктами
  version: 1.0.0
servers:
  - url: https://ITteacherEKP.github.io/product-api-docs
paths:
  /api/products:
    get:
      summary: Получить список продуктов
      responses:
        '200':
          description: Успешный ответ
